// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  //default: [{type: 'autogenerated', dirName: '.'}],
  vanilla: [{type: 'autogenerated', dirName: 'vanilla'}],
  slimefun: [{type: 'autogenerated', dirName: 'slimefun'}],
};

module.exports = sidebars;
