// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  vanilla: [
    {
      type: 'autogenerated',
      dirName: 'vanilla',
    }
  ],
  slimefun: [
    {
      type: 'autogenerated',
      dirName: 'slimefun',
    }
  ],
};

export default sidebars;
